In [1]:
import numpy as np

In [5]:
#define functions
#Used to specify location of car and where the headlights are pointing
def location(a,b):
       """Create a vector that defines location a,b,1"""
       return np.matrix([[a],[b],[1]])

#Translate
def T(c,d):
  """Return a 3x3 matrix which translates x by a and y by b"""
  return np.matrix([[1,0,c], [0,1,d],[0,0,1]])

#Rotate around origin
def R(phi):
  """Return a 3x3 matrix which translates around the origin by angle phi"""
  return np.round(np.matrix([[np.cos(np.deg2rad(phi)), -1*np.sin(np.deg2rad(phi)), 0], [np.sin(np.deg2rad(phi)), np.cos(np.deg2rad(phi)), 0], [0, 0, 1] ]),5)

#Rotate in place
def RabByPhi(a,b,phi, T, R):
  """Return a 3x3 matrix which rotates the car at location a,b by 90 degrees."""
  return T(a,b) * R(phi) * T(-a, -b)

In [11]:
#Case 1
car1 = location(3,0)
light1 = location(3,1)

T(3,3)*R(270)*car1
T(3,3)*R(270)*light1

matrix([[4.],
        [0.],
        [1.]])

In [13]:
#Someone pointing out the passenger side window is pointing towards
pointing_at1 = location(4,0)
T(3,3)*R(270)*pointing_at1

matrix([[ 3.],
        [-1.],
        [ 1.]])

In [16]:
#Case 1B
car1b = location(3,2)
light1b = location(3,3)

In [17]:
T(3,2)*R(270)*T(-3,-2)*car1b

matrix([[3.],
        [2.],
        [1.]])

In [18]:
T(3,2)*R(270)*T(-3,-2)*light1b

matrix([[4.],
        [2.],
        [1.]])

In [21]:
#this is how the inplace function was built
RabByPhi(3,2,270,T,R)*car1b

matrix([[3.],
        [2.],
        [1.]])

In [25]:
RabByPhi(3,2,270,T,R)*light1b

matrix([[4.],
        [2.],
        [1.]])

In [26]:
#Someone pointing out the passenger side window is pointing towards
pointing_at1b = location(4,2)
RabByPhi(3,2,270,T,R)*pointing_at1b

matrix([[3.],
        [1.],
        [1.]])

In [27]:
#Case 2
car2 = location(3,0)
light2 = location(3,1)

In [28]:
T(1,-2)*R(180)*car2

matrix([[-2.],
        [-2.],
        [ 1.]])

In [29]:
T(1,-2)*R(180)*light2

matrix([[-2.],
        [-3.],
        [ 1.]])

In [30]:
#Case 3
car3 = location(3,0)
light3 = location(3,1)

In [31]:
back_into_garage = T(0,1)*RabByPhi(-2,-3,90,T,R)*T(-2,0)*RabByPhi(0,-3,-90,T,R)*T(0,-3)*RabByPhi(0,0,90,T,R)*T(-3,0)*RabByPhi(3,0,90,T,R)
back_into_garage

matrix([[-1.,  0.,  1.],
        [ 0., -1., -2.],
        [ 0.,  0.,  1.]])

In [33]:
back_into_garage*car3

matrix([[-2.],
        [-2.],
        [ 1.]])

In [34]:
back_into_garage*light3

matrix([[-2.],
        [-3.],
        [ 1.]])