In [1]:
import numpy as np

In [2]:
top_left = np.matrix([[-1],[1]])

In [3]:
top_right = np.matrix([[1],[1]])

In [4]:
bottom_left = np.matrix([[-1],[-1]])

In [5]:
bottom_right = np.matrix([[1],[-1]])

In [6]:
def transformation(transform_matrix):
    if np.array_equal(transform_matrix*top_left,top_left) == False:
        print('top_left changed to')
        print(transform_matrix*top_left)
    if np.array_equal(transform_matrix*top_right,top_right) == False:
        print('top_right changed to')
        print(transform_matrix*top_right)
    if np.array_equal(transform_matrix*bottom_right,bottom_right) == False:
        print('bottom_right changed to')
        print(transform_matrix*bottom_right)
    if np.array_equal(transform_matrix*bottom_left,bottom_left) == False:
        print('bottom_left changed to')
        print(transform_matrix*bottom_left)

In [7]:
#R_n is rotation by n degrees
#F_ is flip over one of 4 axes of a square (horizontal, vertical, positive slope, negative slope axes)

In [8]:
R_0 = np.matrix([[1,0],[0,1]])

In [9]:
R_90 = np.matrix([[0,-1],[1,0]])

In [10]:
R_180 = np.matrix([[-1,0],[0,-1]])

In [11]:
R_270 = np.matrix([[0,1],[-1,0]])

In [12]:
F_horiz = np.matrix([[1,0],[0,-1]])

In [13]:
F_vert = np.matrix([[-1,0],[0,1]])

In [14]:
F_neg = np.matrix([[0,-1],[-1,0]])

In [15]:
F_pos = np.matrix([[0,1],[1,0]])

In [16]:
transformation(R_0)

In [17]:
transformation(R_90)

top_left changed to
[[-1]
 [-1]]
top_right changed to
[[-1]
 [ 1]]
bottom_right changed to
[[1]
 [1]]
bottom_left changed to
[[ 1]
 [-1]]


In [18]:
transformation(R_180)

top_left changed to
[[ 1]
 [-1]]
top_right changed to
[[-1]
 [-1]]
bottom_right changed to
[[-1]
 [ 1]]
bottom_left changed to
[[1]
 [1]]


In [19]:
transformation(R_270)

top_left changed to
[[1]
 [1]]
top_right changed to
[[ 1]
 [-1]]
bottom_right changed to
[[-1]
 [-1]]
bottom_left changed to
[[-1]
 [ 1]]


In [20]:
transformation(F_horiz)

top_left changed to
[[-1]
 [-1]]
top_right changed to
[[ 1]
 [-1]]
bottom_right changed to
[[1]
 [1]]
bottom_left changed to
[[-1]
 [ 1]]


In [21]:
transformation(F_vert)

top_left changed to
[[1]
 [1]]
top_right changed to
[[-1]
 [ 1]]
bottom_right changed to
[[-1]
 [-1]]
bottom_left changed to
[[ 1]
 [-1]]


In [22]:
transformation(F_neg)

top_right changed to
[[-1]
 [-1]]
bottom_left changed to
[[1]
 [1]]


In [23]:
transformation(F_pos)

top_left changed to
[[ 1]
 [-1]]
bottom_right changed to
[[-1]
 [ 1]]
